### ISSUE TITLE
Install problems with conda

### ISSUE THREAD

**Issue by jgout** [bjodah/pyodeint#14]
Hi,

I was trying to install your package with conda (just as described in the instructions), but the installation process stopped with the following message

```
$ conda install -c bjodah pyodeint pytest
Fetching package metadata: ......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - numpy (target=numpy-1.10.4-py35_1.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - pip (target=pip-8.1.0-py35_0.tar.bz2) -> python 2.7*|3.4*
  - pip (target=pip-8.1.0-py35_0.tar.bz2) -> wheel
  - pyodeint -> numpy *|1.9*
  - pyodeint -> python 2.7*|3.4*
  - pytest -> python 2.7*|3.4*
  - python 3.5*
  - setuptools (target=setuptools-20.2.2-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - wheel (target=wheel-0.29.0-py35_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*
Use "conda info <package>" to see the dependencies for each package.

```

I used a clean environment with pyhton=3.5 and the numpy package installed.
Any hints?

**Comment by bjodah** [comment]
I simply had not built the recipe for 3.5 since I haven't started using 3.5 myself yet.
I just built it for 3.5 and pushed to my channel. I am also updating the release script to always build for 2.7, 3.4 and 3.5 onwards.

Let me know if it works for you. Here is the recipe for 0.6.0 if you need to tweak something:
http://hera.physchem.kth.se/~pyodeint/conda-recipes/conda-recipe-0.6.0/

**Comment by jgout** [comment]
Great, thank you for the quick fix! The install works fine now.

I am looking forward to test out your package.

**Comment by bjodah** [comment]
Great to hear!
